name: Barbara
favicon: null
layout_spectrum: 0.26993866357952356
typography_spectrum: 0.80985
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eeede8'
    - '#9aa6a4'
    - '#192a2c'
    - '#295c61'
    - '#52787c'
  brandStrength: 0.7239342853426933
  lightness: 0.4006043935660273
  saturation: 0.44328294484876096
  rhythmicContrast: 0.9446106811519712
purpose: []
